## This configuration was generated by terraform-provider-oci

resource oci_autoscaling_auto_scaling_configuration export_autoscaling-config-20220621-1106 {
  auto_scaling_resources {
    id   = oci_core_instance_pool.export_instance-pool-20220621-1105.id
    type = "instancePool"
  }
  compartment_id       = var.compartment_ocid
  cool_down_in_seconds = "300"
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-21T02:07:34.487Z"
  }
  display_name = "autoscaling-config-20220621-1106"
  freeform_tags = {
  }
  is_enabled = "true"
  policies {
    capacity {
      initial = "1"
      max     = "3"
      min     = "1"
    }
    display_name = "autoscaling-policy-20220621-1106"
    #execution_schedule = <<Optional value not found in discovery>>
    is_enabled  = "true"
    policy_type = "threshold"
    #resource_action = <<Optional value not found in discovery>>
    rules {
      action {
        type  = "CHANGE_COUNT_BY"
        value = "-1"
      }
      display_name = "conditiondetails20220621020734"
      metric {
        metric_type = "CPU_UTILIZATION"
        threshold {
          operator = "LT"
          value    = "10"
        }
      }
    }
    rules {
      action {
        type  = "CHANGE_COUNT_BY"
        value = "1"
      }
      display_name = "conditiondetails20220621020734"
      metric {
        metric_type = "CPU_UTILIZATION"
        threshold {
          operator = "GT"
          value    = "30"
        }
      }
    }
  }
}

