## This configuration was generated by terraform-provider-oci

data oci_identity_availability_domain export_nidW-AP-SEOUL-1-AD-1 {
  compartment_id = var.compartment_ocid
  ad_number      = "1"
}
resource oci_file_storage_file_system export_WordPressFilesystem {
  availability_domain = data.oci_identity_availability_domain.export_nidW-AP-SEOUL-1-AD-1.name
  compartment_id      = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-16T12:54:37.452Z"
  }
  display_name = "WordPressFilesystem"
  freeform_tags = {
  }
  kms_key_id = ""
  #source_snapshot_id = <<Optional value not found in discovery>>
}

resource oci_file_storage_mount_target export_WordPressMountTarget {
  availability_domain = data.oci_identity_availability_domain.export_nidW-AP-SEOUL-1-AD-1.name
  compartment_id      = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-16T12:56:55.381Z"
  }
  display_name = "WordPressMountTarget"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.4.188"
  nsg_ids = [
    oci_core_network_security_group.export_WordPressFSSSecurityGroup.id,
  ]
  subnet_id = oci_core_subnet.export_fss_private_subnet.id
}

