## This configuration was generated by terraform-provider-oci

resource oci_core_console_history export_console-history-20220616-2212 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-16T13:12:44.913Z"
  }
  display_name = "console-history-20220616-2212"
  freeform_tags = {
  }
  instance_id = oci_core_instance.export_BastionVM.id
}

resource oci_core_image export_WordPress_instance_image {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T13:26:10.635Z"
  }
  display_name = "WordPress_instance_image"
  freeform_tags = {
  }
  #image_source_details = <<Optional value not found in discovery>>
  #instance_id = <<Optional value not found in discovery>>
  launch_mode = "PARAVIRTUALIZED"
}

resource oci_core_instance_configuration export_instance-config-20220621-1102 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-21T02:05:11.847Z"
  }
  display_name = "instance-config-20220621-1102"
  freeform_tags = {
  }
  instance_details {
    instance_type = "compute"
    launch_details {
      agent_config {
        are_all_plugins_disabled = "false"
        is_management_disabled   = "false"
        is_monitoring_disabled   = "false"
        plugins_config {
          desired_state = "ENABLED"
          name          = "Bastion"
        }
      }
      availability_config {
        recovery_action = "RESTORE_INSTANCE"
      }
      #availability_domain = <<Optional value not found in discovery>>
      #capacity_reservation_id = <<Optional value not found in discovery>>
      compartment_id = var.compartment_ocid
      create_vnic_details {
        assign_private_dns_record = "true"
        assign_public_ip          = "false"
        defined_tags = {
          "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
          "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
          "Oracle-Tags.CreatedOn"                                               = "2022-06-16T13:28:28.636Z"
        }
        display_name = "wordpress2"
        freeform_tags = {
        }
        #hostname_label = <<Optional value not found in discovery>>
        nsg_ids = [
        ]
        #private_ip = <<Optional value not found in discovery>>
        skip_source_dest_check = "false"
        #subnet_id = <<Optional value not found in discovery>>
      }
      #dedicated_vm_host_id = <<Optional value not found in discovery>>
      defined_tags = {
        "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
        "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
        "Oracle-Tags.CreatedOn"                                               = "2022-06-16T13:28:28.456Z"
      }
      display_name = "wordpress2"
      extended_metadata = {
      }
      #fault_domain = <<Optional value not found in discovery>>
      freeform_tags = {
      }
      instance_options {
        are_legacy_imds_endpoints_disabled = "false"
      }
      #ipxe_script = <<Optional value not found in discovery>>
      is_pv_encryption_in_transit_enabled = "false"
      launch_mode                         = "PARAVIRTUALIZED"
      launch_options {
        boot_volume_type = ""
        firmware         = ""
        #is_consistent_volume_naming_enabled = <<Optional value not found in discovery>>
        #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
        network_type            = "PARAVIRTUALIZED"
        remote_data_volume_type = ""
      }
      metadata = {
        "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSurk0F3JEJU0QH00aEmfBlGcReDKBe7UYKWeP++q/2t5RHdIyGcVbiZ1uml2SlkCK+UgWtOkJoCdd4Nf7rDFNZbImsuBbC17NzmhAwcoBBOV6IEUYetplZ2V+6+4kpNWLKMMuqmXod6YkMkMHgL138dG0qdsHnSVVn94nm7f2s80t+wB/uOeNuyfFdurC8xJQHYsXyl3XszAMI3HiZEC6PIXzFqRtG9DZ/ENOLOAM0/5LR/ejpp0lpY0I47IPgcvd1ZunzZfT+0L4I+rb5C2e7q8LLSPYVJxm05iyziTBM54nnxMYnMziSHYrzN4+mhmQB+7ZBQqcbwA0UNkfIWGh ssh-key-2022-06-15"
      }
      #platform_config = <<Optional value not found in discovery>>
      #preemptible_instance_config = <<Optional value not found in discovery>>
      preferred_maintenance_action = ""
      shape                        = "VM.Standard.E3.Flex"
      shape_config {
        baseline_ocpu_utilization = "BASELINE_1_1"
        memory_in_gbs             = "2"
        #nvmes = <<Optional value not found in discovery>>
        ocpus = "1"
      }
      source_details {
        #boot_volume_id = <<Optional value not found in discovery>>
        #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
        image_id    = oci_core_image.export_WordPress_instance_image.id
        source_type = "image"
      }
    }
  }
  #instance_id = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
}

resource oci_core_instance_pool export_instance-pool-20220621-1105 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-21T02:06:39.595Z"
  }
  display_name = "instance-pool-20220621-1105"
  freeform_tags = {
  }
  instance_configuration_id = oci_core_instance_configuration.export_instance-config-20220621-1102.id
  load_balancers {
    backend_set_name = "lb_app01"
    load_balancer_id = oci_load_balancer_load_balancer.export_wordpress_lb.id
    port             = "80"
    vnic_selection   = "PrimaryVnic"
  }
  placement_configurations {
    availability_domain = data.oci_identity_availability_domain.export_nidW-AP-SEOUL-1-AD-1.name
    fault_domains = [
      "FAULT-DOMAIN-1",
      "FAULT-DOMAIN-2",
      "FAULT-DOMAIN-3",
    ]
    primary_subnet_id = oci_core_subnet.export_wp_subnet.id
  }
  size  = "1"
  state = "RUNNING"
}

resource oci_core_instance export_BastionVM {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    #is_live_migration_preferred = <<Optional value not found in discovery>>
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = data.oci_identity_availability_domain.export_nidW-AP-SEOUL-1-AD-1.name
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "true"
    defined_tags = {
      "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
      "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
      "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:55.061Z"
    }
    display_name = "bastionvm"
    freeform_tags = {
    }
    hostname_label = "bastionvm"
    nsg_ids = [
    ]
    private_ip             = "10.0.1.174"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_bastion_public_subnet.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:54.938Z"
  }
  display_name = "BastionVM"
  extended_metadata = {
  }
  fault_domain = "FAULT-DOMAIN-1"
  freeform_tags = {
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSurk0F3JEJU0QH00aEmfBlGcReDKBe7UYKWeP++q/2t5RHdIyGcVbiZ1uml2SlkCK+UgWtOkJoCdd4Nf7rDFNZbImsuBbC17NzmhAwcoBBOV6IEUYetplZ2V+6+4kpNWLKMMuqmXod6YkMkMHgL138dG0qdsHnSVVn94nm7f2s80t+wB/uOeNuyfFdurC8xJQHYsXyl3XszAMI3HiZEC6PIXzFqRtG9DZ/ENOLOAM0/5LR/ejpp0lpY0I47IPgcvd1ZunzZfT+0L4I+rb5C2e7q8LLSPYVJxm05iyziTBM54nnxMYnMziSHYrzN4+mhmQB+7ZBQqcbwA0UNkfIWGh ssh-key-2022-06-15"
    "user_data"           = "H4sIAAAAAAAA/4SSTW+bQBCG70j+D9Q9RnixHcduokQCGwyOPzF2A5dqgbV3DewCu3z++iqRqkbtIcd35pnRI83MGRWICsVtM/Qop2UiSAYLAVLSoOhJDlhJI1i0z/2NvTH03Wm70ByvL70n5YwKThh9lIcDtSf1JEX5DPWkP7sXhGeME/HBQiFgiFNExZN8IQmiMEXPfUgoEQOO+3+n3AJSfkGFYtCQRYReH+VpQMQn4ENZoEaARuEYJQkPC5KJnrQhKfrP7vs3EBAKAsixJIWZDDBLEWBZCAacYwBLgVlBOhT9ilHLv2gPAhhLKMRM7nOOlYJDWdM0TR9vOzgftuHIeI8L7aDp72XtME/GeZ6+Md+rhyv7ao2blRu5lgWma81eT5odvYqJ6o0ypvHDBBTq3a1zGl1vKfUTy3Ziaz8ut7xmR71hZqPyxMqOZJ0lu1JvEmqOdLweqvrpBlsXpJ1RkdIhbw8eJkZOvdVsucarmrKluqtXy87oDs1pZ977lT/bCHS/X67Ch3FUDYPKPOimmu8hKq4qjuFxBgO13aWmZZevzVv4Sglrd93F5kdt1kJ/a4njXs277nx3NfS7jWtGbFgm2aWaEZjf3IVvgJovzj9OHr4scGmebXUz8xcnGsRoE55ebS04efN27DNxdOzJdeY8sLzer63raqpZScan1aizjhW63IDteiDOm6nzcxnF0XiZSH355eWLU0khZjWVFUdmWfgV++8TK0pP+h0AAP//e4m+VSMDAAA="
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.E3.Flex"
  shape_config {
    baseline_ocpu_utilization = ""
    memory_in_gbs             = "1"
    nvmes                     = "0"
    ocpus                     = "1"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.export_wordpress1_source_image_id
    source_type = "image"
  }
  state = "RUNNING"
}

resource oci_core_instance export_wordpress1 {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "ENABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    #is_live_migration_preferred = <<Optional value not found in discovery>>
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = data.oci_identity_availability_domain.export_nidW-AP-SEOUL-1-AD-1.name
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "false"
    defined_tags = {
      "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
      "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
      "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:56.270Z"
    }
    display_name = "wordpress1"
    freeform_tags = {
    }
    hostname_label = "wordpress"
    nsg_ids = [
    ]
    private_ip             = "10.0.2.174"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_wp_subnet.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:56.124Z"
  }
  display_name = "wordpress1"
  extended_metadata = {
  }
  fault_domain = "FAULT-DOMAIN-1"
  freeform_tags = {
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSurk0F3JEJU0QH00aEmfBlGcReDKBe7UYKWeP++q/2t5RHdIyGcVbiZ1uml2SlkCK+UgWtOkJoCdd4Nf7rDFNZbImsuBbC17NzmhAwcoBBOV6IEUYetplZ2V+6+4kpNWLKMMuqmXod6YkMkMHgL138dG0qdsHnSVVn94nm7f2s80t+wB/uOeNuyfFdurC8xJQHYsXyl3XszAMI3HiZEC6PIXzFqRtG9DZ/ENOLOAM0/5LR/ejpp0lpY0I47IPgcvd1ZunzZfT+0L4I+rb5C2e7q8LLSPYVJxm05iyziTBM54nnxMYnMziSHYrzN4+mhmQB+7ZBQqcbwA0UNkfIWGh ssh-key-2022-06-15"
    "user_data"           = "H4sIAAAAAAAA/4SSTW+bQBCG70j+D9Q9RnixHcduokQCGwyOPzF2A5dqgbV3DewCu3z++iqRqkbtIcd35pnRI83MGRWICsVtM/Qop2UiSAYLAVLSoOhJDlhJI1i0z/2NvTH03Wm70ByvL70n5YwKThh9lIcDtSf1JEX5DPWkP7sXhGeME/HBQiFgiFNExZN8IQmiMEXPfUgoEQOO+3+n3AJSfkGFYtCQRYReH+VpQMQn4ENZoEaARuEYJQkPC5KJnrQhKfrP7vs3EBAKAsixJIWZDDBLEWBZCAacYwBLgVlBOhT9ilHLv2gPAhhLKMRM7nOOlYJDWdM0TR9vOzgftuHIeI8L7aDp72XtME/GeZ6+Md+rhyv7ao2blRu5lgWma81eT5odvYqJ6o0ypvHDBBTq3a1zGl1vKfUTy3Ziaz8ut7xmR71hZqPyxMqOZJ0lu1JvEmqOdLweqvrpBlsXpJ1RkdIhbw8eJkZOvdVsucarmrKluqtXy87oDs1pZ977lT/bCHS/X67Ch3FUDYPKPOimmu8hKq4qjuFxBgO13aWmZZevzVv4Sglrd93F5kdt1kJ/a4njXs277nx3NfS7jWtGbFgm2aWaEZjf3IVvgJovzj9OHr4scGmebXUz8xcnGsRoE55ebS04efN27DNxdOzJdeY8sLzer63raqpZScan1aizjhW63IDteiDOm6nzcxnF0XiZSH355eWLU0khZjWVFUdmWfgV++8TK0pP+h0AAP//e4m+VSMDAAA="
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.E3.Flex"
  shape_config {
    baseline_ocpu_utilization = "BASELINE_1_1"
    memory_in_gbs             = "2"
    nvmes                     = "0"
    ocpus                     = "1"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.export_wordpress1_source_image_id
    source_type = "image"
  }
  state = "RUNNING"
}

resource oci_core_instance export_wordpress2 {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "ENABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    #is_live_migration_preferred = <<Optional value not found in discovery>>
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = data.oci_identity_availability_domain.export_nidW-AP-SEOUL-1-AD-1.name
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "false"
    defined_tags = {
      "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
      "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
      "Oracle-Tags.CreatedOn"                                               = "2022-06-16T13:28:28.636Z"
    }
    display_name = "wordpress2"
    freeform_tags = {
    }
    hostname_label = "wordpress2"
    nsg_ids = [
    ]
    private_ip             = "10.0.2.241"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_wp_subnet.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T13:28:28.456Z"
  }
  display_name = "wordpress2"
  extended_metadata = {
  }
  fault_domain = "FAULT-DOMAIN-1"
  freeform_tags = {
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSurk0F3JEJU0QH00aEmfBlGcReDKBe7UYKWeP++q/2t5RHdIyGcVbiZ1uml2SlkCK+UgWtOkJoCdd4Nf7rDFNZbImsuBbC17NzmhAwcoBBOV6IEUYetplZ2V+6+4kpNWLKMMuqmXod6YkMkMHgL138dG0qdsHnSVVn94nm7f2s80t+wB/uOeNuyfFdurC8xJQHYsXyl3XszAMI3HiZEC6PIXzFqRtG9DZ/ENOLOAM0/5LR/ejpp0lpY0I47IPgcvd1ZunzZfT+0L4I+rb5C2e7q8LLSPYVJxm05iyziTBM54nnxMYnMziSHYrzN4+mhmQB+7ZBQqcbwA0UNkfIWGh ssh-key-2022-06-15"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.E3.Flex"
  shape_config {
    baseline_ocpu_utilization = "BASELINE_1_1"
    memory_in_gbs             = "2"
    nvmes                     = "0"
    ocpus                     = "1"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = oci_core_image.export_WordPress_instance_image.id
    source_type = "image"
  }
  state = "RUNNING"
}

resource oci_core_internet_gateway export_internet_gateway {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:49.254Z"
  }
  display_name = "internet_gateway"
  enabled      = "true"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_network_security_group export_WordPressFSSSecurityGroup {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-16T12:56:49.304Z"
  }
  display_name = "WordPressFSSSecurityGroup"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_network_security_group_security_rule export_WordPressFSSSecurityGroup_network_security_group_security_rule_1 {
  #description = <<Optional value not found in discovery>>
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_WordPressFSSSecurityGroup.id
  protocol                  = "6"
  source                    = "10.0.2.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "111"
      min = "111"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_WordPressFSSSecurityGroup_network_security_group_security_rule_2 {
  #description = <<Optional value not found in discovery>>
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_WordPressFSSSecurityGroup.id
  protocol                  = "6"
  source                    = "10.0.2.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "2050"
      min = "2048"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_WordPressFSSSecurityGroup_network_security_group_security_rule_3 {
  #description = <<Optional value not found in discovery>>
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_WordPressFSSSecurityGroup.id
  protocol                  = "17"
  source                    = "10.0.2.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  udp_options {
    destination_port_range {
      max = "111"
      min = "111"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_WordPressFSSSecurityGroup_network_security_group_security_rule_4 {
  #description = <<Optional value not found in discovery>>
  destination               = "10.0.2.0/24"
  destination_type          = "CIDR_BLOCK"
  direction                 = "EGRESS"
  network_security_group_id = oci_core_network_security_group.export_WordPressFSSSecurityGroup.id
  protocol                  = "6"
  #source = <<Optional value not found in discovery>>
  source_type = ""
  stateless   = "false"
  tcp_options {
    destination_port_range {
      max = "111"
      min = "111"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_WordPressFSSSecurityGroup_network_security_group_security_rule_5 {
  #description = <<Optional value not found in discovery>>
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_WordPressFSSSecurityGroup.id
  protocol                  = "17"
  source                    = "10.0.2.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  udp_options {
    destination_port_range {
      max = "2048"
      min = "2048"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_WordPressFSSSecurityGroup_network_security_group_security_rule_6 {
  #description = <<Optional value not found in discovery>>
  destination               = "10.0.2.0/24"
  destination_type          = "CIDR_BLOCK"
  direction                 = "EGRESS"
  network_security_group_id = oci_core_network_security_group.export_WordPressFSSSecurityGroup.id
  protocol                  = "17"
  #source = <<Optional value not found in discovery>>
  source_type = ""
  stateless   = "false"
  udp_options {
    destination_port_range {
      max = "111"
      min = "111"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_WordPressFSSSecurityGroup_network_security_group_security_rule_7 {
  #description = <<Optional value not found in discovery>>
  destination               = "10.0.2.0/24"
  destination_type          = "CIDR_BLOCK"
  direction                 = "EGRESS"
  network_security_group_id = oci_core_network_security_group.export_WordPressFSSSecurityGroup.id
  protocol                  = "6"
  #source = <<Optional value not found in discovery>>
  source_type = ""
  stateless   = "false"
  tcp_options {
    destination_port_range {
      max = "2050"
      min = "2048"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_public_ip export_WordPress_public_ip_for_multi_node {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:48.562Z"
  }
  display_name = "WordPress_public_ip_for_multi_node"
  freeform_tags = {
  }
  lifetime      = "RESERVED"
  private_ip_id = oci_core_private_ip.export_VNIC-for-LB-ocid1-loadbalancer-oc1-ap-seoul-1-aaaaaaaalc7lr4vd2amg4gb7dkljkqg7z37bwn2bwsgknx6awlplgxhok72a_1.id
  #public_ip_pool_id = <<Optional value not found in discovery>>
}

resource oci_core_subnet export_wp_subnet {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.2.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:51.433Z"
  }
  dhcp_options_id = oci_core_vcn.export_wpmdsvcn.default_dhcp_options_id
  display_name    = "wp_subnet"
  dns_label       = "wpsub"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_RouteTableViaNATGW.id
  security_list_ids = [
    oci_core_security_list.export_Allow-Public-SSH-Connections-to-WordPress.id,
    oci_core_security_list.export_Allow-HTTP-S-to-WordPress.id,
  ]
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_subnet export_mds_private_subnet {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.3.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:50.309Z"
  }
  dhcp_options_id = oci_core_vcn.export_wpmdsvcn.default_dhcp_options_id
  display_name    = "mds_private_subnet"
  dns_label       = "mdspriv"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_RouteTableViaNATGW.id
  security_list_ids = [
    oci_core_security_list.export_Private.id,
  ]
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_subnet export_fss_private_subnet {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.4.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:50.309Z"
  }
  dhcp_options_id = oci_core_vcn.export_wpmdsvcn.default_dhcp_options_id
  display_name    = "fss_private_subnet"
  dns_label       = "fsspriv"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_RouteTableViaNATGW.id
  security_list_ids = [
    oci_core_vcn.export_wpmdsvcn.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_subnet export_bastion_public_subnet {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.1.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:50.358Z"
  }
  dhcp_options_id = oci_core_vcn.export_wpmdsvcn.default_dhcp_options_id
  display_name    = "bastion_public_subnet"
  dns_label       = "bastionpub"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_route_table.export_RouteTableViaIGW.id
  security_list_ids = [
    oci_core_security_list.export_Allow-Public-SSH-Connections-to-WordPress.id,
  ]
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_subnet export_lb_public_subnet {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:50.309Z"
  }
  dhcp_options_id = oci_core_vcn.export_wpmdsvcn.default_dhcp_options_id
  display_name    = "lb_public_subnet"
  dns_label       = "lbpub"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_route_table.export_RouteTableViaIGW.id
  security_list_ids = [
    oci_core_security_list.export_Allow-HTTP-S-to-WordPress.id,
  ]
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_private_ip export_wordpress1_1 {
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:56.270Z"
  }
  display_name = "wordpress1"
  freeform_tags = {
  }
  hostname_label = "wordpress"
  ip_address     = "10.0.2.174"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-seoul-1.abuwgljrwg6onkzvyebktntaui36owmdydd57gqmospbwtmflcwzg6ltovqa"
}

resource oci_core_private_ip export_wordpress2_2 {
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T13:28:28.636Z"
  }
  display_name = "wordpress2"
  freeform_tags = {
  }
  hostname_label = "wordpress2"
  ip_address     = "10.0.2.241"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-seoul-1.abuwgljrokxclmfmb77pssfkfdf66egn5k7hengxv5ohm2zqaaciepcr43pa"
}

resource oci_core_private_ip export_privateip20220616125835 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "mysql"
    "Oracle-Tags.CreatedOn" = "2022-06-16T12:58:35.337Z"
  }
  display_name = "privateip20220616125835"
  freeform_tags = {
  }
  hostname_label = "drupalmds"
  ip_address     = "10.0.3.36"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-seoul-1.abuwgljrfrxh74yjmvyjnj4zs7t2xnqdx2obzogw4hrcvf53ombvgvpasocq"
}

resource oci_core_private_ip export_vnic20220616125803 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "mysql"
    "Oracle-Tags.CreatedOn" = "2022-06-16T12:58:00.009Z"
  }
  display_name = "vnic20220616125803"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.3.73"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-seoul-1.abuwgljrfrxh74yjmvyjnj4zs7t2xnqdx2obzogw4hrcvf53ombvgvpasocq"
}

resource oci_core_private_ip export_fss-mnt-1000000022348569 {
  defined_tags = {
  }
  display_name = "fss-mnt-1000000022348569"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.4.137"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-seoul-1.abuwgljre2datwlqsfymodpfzr6n34s63cruqoobsng2ie4whzlxpzcxtqna"
}

resource oci_core_private_ip export_fss-mnt-1000000022348569_1 {
  defined_tags = {
  }
  display_name = "fss-mnt-1000000022348569"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.4.140"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-seoul-1.abuwgljrkast64d7cayqjx2sv64vmjutiy6xe6z4q643auwmv5gi76pjampq"
}

resource oci_core_private_ip export_privateip20220616125706 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "fssoc1prod"
    "Oracle-Tags.CreatedOn" = "2022-06-16T12:57:06.840Z"
  }
  display_name = "privateip20220616125706"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.4.188"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-seoul-1.abuwgljre2datwlqsfymodpfzr6n34s63cruqoobsng2ie4whzlxpzcxtqna"
}

resource oci_core_private_ip export_bastionvm {
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:55.061Z"
  }
  display_name = "bastionvm"
  freeform_tags = {
  }
  hostname_label = "bastionvm"
  ip_address     = "10.0.1.174"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-seoul-1.abuwgljrgxlxhxpv6l2pq3v3m3hrrz5fxtjoj4uqduheaggfjtbmq5r2lpna"
}

resource oci_core_private_ip export_VNIC-for-LB-ocid1-loadbalancer-oc1-ap-seoul-1-aaaaaaaalc7lr4vd2amg4gb7dkljkqg7z37bwn2bwsgknx6awlplgxhok72a {
  defined_tags = {
  }
  display_name = "VNIC for LB ocid1.loadbalancer.oc1.ap-seoul-1.aaaaaaaalc7lr4vd2amg4gb7dkljkqg7z37bwn2bwsgknx6awlplgxhok72a"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.0.77"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-seoul-1.abuwgljrq7g4p4msonzhtsylvlljtyhfwj4gigjpki7vvtvt7mkr4yqh6xoq"
}

resource oci_core_private_ip export_VNIC-for-LB-ocid1-loadbalancer-oc1-ap-seoul-1-aaaaaaaalc7lr4vd2amg4gb7dkljkqg7z37bwn2bwsgknx6awlplgxhok72a_1 {
  defined_tags = {
  }
  display_name = "VNIC for LB ocid1.loadbalancer.oc1.ap-seoul-1.aaaaaaaalc7lr4vd2amg4gb7dkljkqg7z37bwn2bwsgknx6awlplgxhok72a"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.0.121"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ap-seoul-1.abuwgljrl4pnfoetns7gbdje7d4dkwtmrqlgtx3sc7uyczqqouncw6rjwvzq"
}

resource oci_core_vcn export_wpmdsvcn {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:48.546Z"
  }
  display_name = "wpmdsvcn"
  dns_label    = "wpmdsvcn"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-wpmdsvcn {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:48.546Z"
  }
  display_name     = "Default DHCP Options for wpmdsvcn"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_wpmdsvcn.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "wpmdsvcn.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_nat_gateway export_nat_gateway {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:49.297Z"
  }
  display_name = "nat_gateway"
  freeform_tags = {
  }
  public_ip_id = "ocid1.publicip.oc1.ap-seoul-1.aaaaaaaa72baxmo7344b5ggr2d4p2yf523u45c5kl4u437muzwsnkusqry6a"
  vcn_id       = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_route_table export_RouteTableViaNATGW {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:50.850Z"
  }
  display_name = "RouteTableViaNATGW"
  freeform_tags = {
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_nat_gateway.id
  }
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_route_table export_RouteTableViaIGW {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:49.859Z"
  }
  display_name = "RouteTableViaIGW"
  freeform_tags = {
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_internet_gateway.id
  }
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-wpmdsvcn {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:48.546Z"
  }
  display_name = "Default Route Table for wpmdsvcn"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_wpmdsvcn.default_route_table_id
}

resource oci_core_security_list export_Allow-HTTP-S-to-WordPress {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:49.364Z"
  }
  display_name = "Allow HTTP(S) to WordPress"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_security_list export_Allow-Public-SSH-Connections-to-WordPress {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:49.219Z"
  }
  display_name = "Allow Public SSH Connections to WordPress"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_security_list export_Private {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:49.197Z"
  }
  display_name = "Private"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      #max = <<Optional value not found in discovery>>
      #min = <<Optional value not found in discovery>>
      source_port_range {
        max = "2050"
        min = "2048"
      }
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "3306"
      min = "3306"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "111"
      min = "111"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "33061"
      min = "33060"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "2050"
      min = "2048"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_wpmdsvcn.id
}

resource oci_core_default_security_list export_Default-Security-List-for-wpmdsvcn {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:48.546Z"
  }
  display_name = "Default Security List for wpmdsvcn"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_wpmdsvcn.default_security_list_id
}

