## This configuration was generated by terraform-provider-oci

resource oci_file_storage_export export_export_1 {
  export_options {
    access                         = "READ_WRITE"
    anonymous_gid                  = "65534"
    anonymous_uid                  = "65534"
    identity_squash                = "NONE"
    require_privileged_source_port = "false"
    source                         = "0.0.0.0/0"
  }
  export_set_id  = "ocid1.exportset.oc1.ap_seoul_1.aaaaaa4np2tbxayynfrw4llqojxwiotboawxgzlpovwc2mjnmfsc2mia"
  file_system_id = oci_file_storage_file_system.export_WordPressFilesystem.id
  path           = "/sharedwp"
}

