## This configuration was generated by terraform-provider-oci

resource oci_monitoring_alarm export_CPU-Alam-InstancePool {
  body           = "CPU utilization exceeded 90%"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-21T03:04:35.858Z"
  }
  destinations = [
    oci_ons_notification_topic.export_Notification_CPU.id,
  ]
  display_name = "CPU Alam-InstancePool"
  freeform_tags = {
  }
  is_enabled                       = "true"
  message_format                   = "ONS_OPTIMIZED"
  metric_compartment_id            = var.compartment_ocid
  metric_compartment_id_in_subtree = "false"
  namespace                        = "oci_computeagent"
  pending_duration                 = "PT1M"
  query                            = "CpuUtilization[1m]{instancePoolId = \"ocid1.instancepool.oc1.ap-seoul-1.aaaaaaaa2estse5ygdneg6snaawxkqueceizmfjovvnhfsi3ywkpsu37fpna\"}.mean() > 90"
  #repeat_notification_duration = <<Optional value not found in discovery>>
  resolution = "1m"
  #resource_group = <<Optional value not found in discovery>>
  severity = "CRITICAL"
}

