## This configuration was generated by terraform-provider-oci

resource oci_mysql_mysql_db_system export_WordPressMDS {
  #admin_password = <<Optional value not found in discovery>>
  #admin_username = <<Optional value not found in discovery>>
  availability_domain = data.oci_identity_availability_domain.export_nidW-AP-SEOUL-1-AD-1.name
  backup_policy {
    #defined_tags = <<Optional value not found in discovery>>
    freeform_tags = {
    }
    is_enabled        = "false"
    retention_in_days = "7"
    window_start_time = "19:43"
  }
  compartment_id          = var.compartment_ocid
  configuration_id        = "ocid1.mysqlconfiguration.oc1..aaaaaaaalwzc2a22xqm56fwjwfymixnulmbq3v77p5v4lcbb6qhkftxf2trq"
  crash_recovery          = "ENABLED"
  data_storage_size_in_gb = "50"
  defined_tags = {
    "ArchitectureCenter\deploy-wordpress-cms-with-mysql-dbs-85d2.release" = "1.5"
    "Oracle-Tags.CreatedBy"                                               = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn"                                               = "2022-06-16T12:56:55.593Z"
  }
  deletion_policy {
    automatic_backup_retention = "DELETE"
    final_backup               = "SKIP_FINAL_BACKUP"
    is_delete_protected        = "false"
  }
  description  = "MySQL DB System for Drupal-MDS"
  display_name = "WordPressMDS"
  fault_domain = "FAULT-DOMAIN-1"
  freeform_tags = {
  }
  hostname_label      = "DrupalMDS"
  ip_address          = "10.0.3.36"
  is_highly_available = "false"
  maintenance {
    window_start_time = "SUNDAY 14:30"
  }
  mysql_version = "8.0.29"
  port          = "3306"
  port_x        = "33060"
  shape_name    = "MySQL.VM.Standard.E3.1.8GB"
  #shutdown_type = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
  state     = "ACTIVE"
  subnet_id = oci_core_subnet.export_mds_private_subnet.id
}

