## This configuration was generated by terraform-provider-oci

resource oci_ons_notification_topic export_Notification_CPU {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-21T02:55:16.766Z"
  }
  description = "Notification-Mail : CPU"
  freeform_tags = {
  }
  name = "Notification_CPU"
}

resource oci_ons_subscription export_subscription_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-21T02:55:17.216Z"
  }
  delivery_policy = "{\"backoffRetryPolicy\":{\"maxRetryDuration\":7200000,\"policyType\":\"EXPONENTIAL\"}}"
  endpoint        = "iljinjang84@gmail.com"
  freeform_tags = {
  }
  protocol = "EMAIL"
  topic_id = oci_ons_notification_topic.export_Notification_CPU.id
}

