## This configuration was generated by terraform-provider-oci

resource oci_identity_tag_namespace export_ArchitectureCenter-deploy-wordpress-cms-with-mysql-dbs-85d2 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-16T12:54:37.235Z"
  }
  description = "ArchitectureCenterTagNamespace"
  freeform_tags = {
  }
  is_retired = "false"
  name       = "ArchitectureCenter\\deploy-wordpress-cms-with-mysql-dbs-85d2"
}

resource oci_identity_tag export_release {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/iljinjang84@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-06-16T12:54:47.872Z"
  }
  description = "ArchitectureCenterTag"
  freeform_tags = {
  }
  is_cost_tracking = "false"
  is_retired       = "false"
  name             = "release"
  tag_namespace_id = oci_identity_tag_namespace.export_ArchitectureCenter-deploy-wordpress-cms-with-mysql-dbs-85d2.id
  validator {
    validator_type = "ENUM"
    values = [
      "release",
      "1.5",
    ]
  }
}

